name: Build Wheels and Upload to PyPI

on:
  workflow_dispatch:
    inputs:
      prerelease_version:
        description: 'Prerelease Version'
        required: true
        default: ''
        type: string

      test_pypi:
        description: 'Release to Test PyPI'
        required: true
        default: true
        type: boolean

      pypi:
        description: 'Release to PyPI'
        required: true
        default: false
        type: boolean

env:
  CIBW_SKIP: cp27-* cp33-* cp34-* cp35-* pp27* pp36* pp37* pp38* pp39* pp310* pp311* *-musllinux*
  # CIBW_SKIP: cp27-* cp33-* cp34-* cp35-* cp36-* cp37-* cp38-* cp39-* cp310-* pp27* pp36* pp37* pp38* pp39* pp310* pp311* *-musllinux*

jobs:
  build_wheels:
    name: Build wheels on ${{matrix.arch}} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest]
        # python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [auto]
        include:
          - os: ubuntu-20.04
            arch: aarch64

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if:  ${{ matrix.arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v1

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.3
        # to supply options, put them in 'env', like:
        env:
          CIBW_ARCHS_LINUX: ${{matrix.arch}}
          CIBW_BEFORE_BUILD: pip install oldest-supported-numpy

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact   # prevents extra directory
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        if: inputs.test_pypi
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verify_metadata: false

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        if: inputs.pypi
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verify_metadata: false
