name: Publish to Test PyPI
run-name: "Publish to Test PyPI: ${{ github.ref_type }} ${{ github.ref_name }}"

# Controls when the workflow will run - manually triggered
# Note that if this workflow is run without a tag on the HEAD commit, the
# version will be marked ".devN" where N is the number of commits since the
# last version tag.
on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.arch }} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [auto]
        include:
          - os: ubuntu-20.04
            arch: aarch64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        if:  ${{ matrix.arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        # to supply options, put them in 'env', like:
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: '>=3.9'
          CIBW_SKIP: 'pp* *musllinux* *cp27mu*'
          CIBW_ARCHS: 'auto64'
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_ARCHS_MACOS: 'x86_64 arm64'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: artifact-*
          merge-multiple: true

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          verify-metadata: false
