# This workflow compiles CSPICE for many architectures and publishes a branch
# to PyPi

name: Publish to PyPI
run-name: Publish to PyPI triggered by ${{ github.ref_type }} ${{ github.ref_name }}

# Controls when the workflow will run - push of a "v*" tag
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  # We have to skip *i686 because numpy doesn't currentl have pre-built wheels
  # for Python 3.12 as of 10/20/2023. We could try adding it back later.
  # See https://github.com/numpy/numpy/issues/24703
  CIBW_SKIP: cp27-* cp33-* cp34-* cp35-* cp36-* pp* *i686 *-musllinux*

jobs:
  build_wheels:
    name: Build wheels on ${{matrix.arch}} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [ '3.7', '3.8', '3.9', '3.10', '3.11', '3.12' ]
        arch: [auto]
        include:
          - os: ubuntu-20.04
            arch: aarch64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        if:  ${{ matrix.arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        # to supply options, put them in 'env', like:
        env:
          CIBW_ARCHS_LINUX: ${{matrix.arch}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact   # prevents extra directory
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verify-metadata: false
